<?php

/**
 * User: Nadil
 * Date: 6/1/2016
 * Time: 2:57 PM
 */

namespace humhub\modules\news\controllers;

use humhub\modules\content\components\ContentContainerController;
use humhub\modules\content\models\Content;
use humhub\modules\file\models\File;
use humhub\modules\news\models\EditForm;

use humhub\modules\news\models\News;
use humhub\modules\news\models\NewsLayouts;

use humhub\modules\user\models\User;
use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;
use  humhub\modules\news\models\UploadForm;
use yii\web\HttpException;

class NewsController extends ContentContainerController
{

    public function actions()
    {
        return array(
            'stream' => array(
                'class' => \humhub\modules\news\components\StreamAction::className(),
                'mode' => \humhub\modules\news\components\StreamAction::MODE_NORMAL,
                'contentContainer' => $this->contentContainer
            ),
        ); // TODO: Change the autogenerated stub
    }

    public function actionCreate()
    {

        if (!$this->contentContainer->permissionManager->can(new \humhub\modules\news\permissions\CreateNews())) {
            throw new HttpException(400, 'Access denied!');
        }

        $fileList = Yii::$app->request->post('fileList');
        $newsModel = new News();
        if ($fileList == "") {
        } else {
           // $fileItems = explode(",", $fileList); -- version before 1.2
           // $imageGuid = $fileItems[1];
          //for 1.2 +
             $imageGuid = $fileList[0];
            $newsModel->imgfile = $imageGuid;

        }

        $text = Yii::$app->request->post('text');
        $newsModel->title = Yii::$app->request->post('title');
        $newsModel->text = $text;
        $newsModel->created_at = date('Y-m-d h:i:s ', time());

        $authorList = Yii::$app->request->post('changeAuthor');
        if ($authorList == "") {
            $newsModel->created_by = Yii::$app->user->id;
//            return "inga";
        } else {
            $authors = explode(",", $authorList);
            $assgnedAuthor = $authors[0];
            $authorId = User::findOne(['guid' => $assgnedAuthor]);
            $newsModel->created_by = $authorId->id;
            $newsModel->content->created_by = $authorId->id;
            $newsModel->content->created_by  = $authorId->id;
        }

        $parsedLayoutId = Yii::$app->request->post('lay');
        if ($parsedLayoutId != "") {
            $newsLayout = NewsLayouts::findOne([
                'id' => $parsedLayoutId
            ]);
        } else {
            $newsLayout = NewsLayouts::findOne(['name' => 'default']);
        }

        $newsModel->layout_id = $newsLayout->id;
        \humhub\modules\file\models\File::attachPrecreated($newsModel, $imageGuid);
        return \humhub\modules\news\widgets\WallCreateForm::create($newsModel, $this->contentContainer);
    }

    public function actionUpload()
    {

        $model = new UploadForm();
        if (\Yii::$app->request->isPost) {

            $newsModel = new News();
            $text = Yii::$app->request->post('text');
            $model->title = Yii::$app->request->post('title');
            $model->text = $text;
            $model->created_at = date('Y-m-d h:i:s ', time());
            $model->created_by = Yii::$app->user->id;
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->upload()) {
                $model->imageFile->saveAs('/uploads/' . rand() . '.' . $model->imageFile->extension);
                return;
            }
            return \humhub\modules\news\widgets\WallCreateForm::create($model, $this->contentContainer);
        }

        return $this->render('testupload', ['model' => $model]);

    }

    public function actionShow()
    {

        $newsForm = new EditForm();
        $model = new News();
        $layouts = NewsLayouts::find()
            ->all();
        $userId = Yii::$app->user->id;;

        return $this->render('show', array(
            'model' => $model,
            'contentContainer' => $this->contentContainer,
            'layouts' => $layouts
        ));
    }

    public function actionView()
    {
        $idnews = (int)Yii::$app->request->getQueryParam('id');
        $news = News::findOne(['id' => $idnews]);
        if ($news) {
            $user = User::findOne(['id' => $news->created_by]);

            return $this->render('view', ['news' => $news, 'user' => $user, 'space' => $this->contentContainer]);
        } else {
            $this->redirect(Url::toRoute('/news/news/show'));
        }

    }

    public function actionDemo()
    {
        return $this->render('test', ['cont' => $this->contentContainer]);
    }

    public function actionTestupload()
    {
        \Yii::$app->response->format = 'json';

        $model = new \humhub\models\forms\UploadProfileImage();
        $json = array();

        $files = \yii\web\UploadedFile::getInstancesByName('bannerfilestwo');
        $file = $files[0];
        $model->image = $file;
        $model->image->saveAs(rand(1000, 10000) . '.' . $file->extension);
    }

    public function actionEdit()
    {

        $id = Yii::$app->request->get('id');
        $model = News::findOne(['id' => $id]);
        $edited = false;
        $layouts = NewsLayouts::find()
            ->all();
        if ($model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            $result = [];
            if ($model->validate()) {
                $authorInputId="news_input_author".$id;
                $authorList = Yii::$app->request->post($authorInputId);
                $authorChanged=false;
                if(!($authorList=="")){
                    $authors = explode(",", $authorList);
                    $assgnedAuthor = $authors[0];
                    $authorId=User::findOne(['guid'=>$assgnedAuthor]);
                    $model->content->created_by =$authorId->id;
                    $authorChanged=true;
                }
                $parsedLayoutId=Yii::$app->request->post('news_input_layout');
                if($parsedLayoutId != ""){
                    $newsLayout = NewsLayouts::findOne([
                        'id' => $parsedLayoutId
                    ]);
                    if(is_null($newsLayout)){
                        $newsLayout=NewsLayouts::findOne(['name'=>'default']);
                        $model->layout_id=$newsLayout->id;
                    }else{
                        $model->layout_id=$newsLayout->id;
                    }
                }

                $editguid=Yii::$app->request->post('editguid');
                if($editguid != "" ){

                     if( $model->imageFile==""){
                       $model->imgfile=$editguid;
                       \humhub\modules\file\models\File::attachPrecreated($model, $editguid);

                     } else {
                       if ($model->imageFile != $editguid) {
                           $model->imageFile = $editguid;
                           \humhub\modules\file\models\File::attachPrecreated($model, $editguid);

                       }
                    }

                }
                if($model->save()){
                    $model = News::findOne(['id' => $id]);
                    $result['success'] = true;
                    $result['output'] = $this->renderAjaxContent($model->getWallOut(['justEdited' => false]));
                }
            } else {
                $result['errors'] = $model->getErrors();
            }
            return $result;
        }
        return $this->renderAjax('edit', ['news' => $model,
            'edited' => $edited,
            'layouts'=>$layouts,
            'contentContainer' => $this->contentContainer,]);

    }

    public function actionReload()
    {
        $id = Yii::$app->request->get('id');
        $model = News::findOne(['id' => $id]);
        return $this->renderAjaxContent($model->getWallOut(['justEdited' => true]));
    }

    public function actionTest()
    {
        $request = Yii::$app->request;
        $model = new News();
        if ($model->load($request->post()) && $model->validate()) {
            $newsModel = new News();
            $newsModel->title = Yii::$app->request->post('title');
            $newsModel->text = Yii::$app->request->post('text');;
            $newsModel->created_at = date('Y-m-d h:i:s ', time());
            $newsModel->created_by = Yii::$app->user->id;
            $newsModel->file = UploadedFile::getInstance($newsModel, 'file');
            $imageName = rand();
            $newsModel->file->saveAs($imageName . $newsModel->file->extension);
            $newsModel->imgfile = '/uploads/news/' . $imageName . $newsModel->file->extension;
            $newsModel->save();
        }
        return $this->render('test', ['model' => $model]);
    }

    public function actionTestcreate()
    {

    }

    public function actionRemoveimage()
    {
        $id = Yii::$app->request->get('id');
        $image = Yii::$app->request->get('image');
        $file =new File();
         if($file->canDelete()){

             $news=News::findOne([
                'id'=>$id
             ]);
             $news->imgfile="";
             $news->update();
             $imageFile=File::findOne([
                 'guid'=>$image,
             ]);
             $imageFile->delete();
         }
    }

    public function actionEditimage() {

    }

}
